# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"C\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"1\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2K\n\x0eOrderProcessor\x12\x39\n\x0cProcessOrder\x12\x13.order.OrderRequest\x1a\x14.order.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=22
  _globals['_ORDERREQUEST']._serialized_end=89
  _globals['_ORDERRESPONSE']._serialized_start=91
  _globals['_ORDERRESPONSE']._serialized_end=140
  _globals['_ORDERPROCESSOR']._serialized_start=142
  _globals['_ORDERPROCESSOR']._serialized_end=217
# @@protoc_insertion_point(module_scope)
