# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.62.2'
# Runtime version validation removed for compatibility with pinned grpcio.
# Ensure `grpcio` and `grpcio-tools` pinned versions remain aligned to avoid
# subtle incompatibilities in generated code.


class OrderProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOrder = channel.unary_unary(
                '/order.OrderProcessor/ProcessOrder',
                request_serializer=order__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__pb2.OrderResponse.FromString,
                _registered_method=True)


class OrderProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOrder,
                    request_deserializer=order__pb2.OrderRequest.FromString,
                    response_serializer=order__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.OrderProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderProcessor/ProcessOrder',
            order__pb2.OrderRequest.SerializeToString,
            order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
